### ISSUE TITLE
Vectorization

### ISSUE THREAD

**Issue by bizzinho** [SPLIfA/snow#1]
Hey Leif, can you add more comments re what's happening in the 'vectorization' part and right after? Maybe with better documentation I get it just by reading.

**Comment by ltdeck** [comment]
Hi Dave,

thanks a lot for starting the work here. I am now trying to get familiar with GitHub and python. I made an account here, too: ltdeck. I think I write this message via this account. 

Let me add some comments to the vectorization part. I will summarize the key concepts here: 
Basically the key idea is to create a big interaction matrix (called HEINT) with (number of vials) times (number of vials) elements, where each entry corresponds to an interaction between vials. 

The expression q = HEINT*T_time + HSEXT*T_i(i) then calculates all energy flows for a timestep. T_time is the temperature vector containing the temperature of all vials in the previous timestep. T_i (or T_ext) is the external temperature at the given time, multiplied with a HSEXT vector. HSEXT specifies the number of contact surfaces of each vial with the external cooling medium. 

To calculate the interaction matrix HEINT, I add up the individual contributions. The diagonal elements correspond to the "eigen"temperature of each vial, which is required because we care about temperature difference when calculating energy flows. It thus is negative and we need to multiply with the number of heat flows (i.e. surfaces) we have, i.e. 4 or 6 for 2D and 3D. Then there are interactions with neighbors in x,y and z direction which need to be inserted at the right position of the matrix. With this information, I construct a first interaction matrix INT, which simply counts the number of interactions of each vial. By defining

EXT = - sum(INT)

We get the number of contact surfaces with the external medium for each vial. We remove these surfaces from INT by saying 

INT = INT + diag(EXT);

The heat flows are based on heat transfer coefficients, for the 2D case we have two types:

HTEXT = A.*kext.*Dt;
HTINT = A.*kint.*Dt;

We multiply this with INT and EXT to get two heat flow matrizes:

HINT = sparse(INT.*HTINT); 

HEXT = EXT.*HTEXT; 

Since KS is assumed to be stochastic, we need to do some calculations within the parfor loop. For each simulation in the parfor loop, the KS values are different. 

The heat transfer contribution of the shelf is:

HS =  sparse(KS'.*A.*Dt); where KS is the vector containing all KS coefficients for all vials.

Since heat transfer via shelf is based on external temperature, we combine it with the EXT term to:

HSEXT = (HEXT+HS)'

Secondly, we now can define HEINT, where we need to account for the additional external terms by subtracting diagonal elements:

HEINT = HINT - diag(HEXT) - diag(HS)

Then we can calculate the heat flow values for each timestep simply by 

q = HEINT*T_time + HSEXT*T_i(i);

This is the approach in the 2D case. In 3D it is similar, but we do not have a shelf and we define direction dependent heat transfer coefficients.

I hope this helps. Let me know if you have any questions.

**Comment by bizzinho** [comment]
sorry @ltdeck , I was not clear. can you add those comments directly in the code and push them to the feature/pythonpackage branch :) now that you have already answered the question it's not so urgent. But maybe a good practice ;)

**Comment by ltdeck** [comment]
Sure @bizzinho, I will try.

**Comment by ltdeck** [comment]
This comment is a remainder from an older version that I forgot to remove; when developing the vectorization I initially wrote it in a way that it only worked when all heat transfer coefficients had the same value. 

This is not true anymore and the code works for different values of all coefficients now. So please ignore this comment.

**Comment by ltdeck** [comment]
Sounds good, I will have a look. I will send you something

**Comment by bizzinho** [comment]
This is now implemented and I think I understood it.
