### ISSUE TITLE
Controlled nucleation of non-supercooled vials

### ISSUE THREAD

**Issue by bizzinho** [SPLIfA/snow#4]
Hey @ltdeck, asking myself what the right behavior is for vials that are not supercooled at the end of holding, when controlled nucleation would be triggered.

Right now, only vials that are both liquid and supercooled are nucleated by controlled nucleation at the end of holding. What is the right behavior for vials that are not supercooled yet?

1. They should nucleate spontaneously whenever the dice decide
2. They should nucleate as soon as they become supercooled
3. They should nucleate as soon as they become supercooled if that time is within X seconds of the nucleation trigger, otherwise they should nucleate spontaneously whenever the dice decide.

**Comment by ltdeck** [comment]
Hey @bizzinho :
I think that's a good point and there is no clear answer for that. Somewhere I mention nucleation efficiency in the paper and discuss this a bit. If you use ice-fog method, nothing would happen and they nucleate later spontaneously. This is in fact the big problem of the method, because you still need a supercooling of 2-3K that the seeds of ice actually grow. If you use vacuum induced nucleation, the vial is cooled down further by evaporation so that nucleation is induced even if it is not supercooled. 

Since we do not use a nucleation efficiency (yet) in the work, I would recommend to let non-supercooled vials nucleate spontaneously. Perhaps you can build in a counter so we know how many and which vials did so?

**Comment by bizzinho** [comment]
okidoki, that's the behavior right now and the counting can be done easily using the existing methods!
